version: '3.8'
services:
  web:
    build: .
    restart: always
    command: "/usr/src/app/entrypoint.sh db python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./referal:/usr/src/app/referal
      - ./referal_app:/usr/src/app/referal_app
      - ./user:/usr/src/app/user
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
     - db
     - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
      
volumes:
  postgres_data:
  redisdata: